[versions]
androidCore = "1.12.0"
androidLifeCycle = "2.7.0"
androidArchVersion = "2.2.0"
googleCore = "1.41.0"
composeBom = "androidx.compose:compose-bom:2023.10.01"
composeActivity = "1.8.2"
composeConstraintLayout = "1.0.1"
hiltVersion = "2.50"
hiltNavigation = "1.1.0"
roomVersion = "2.6.1"
navVersion = "2.7.6"
junit = "4.13.2"

[libraries]
# Android Core
android-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidCore" }
# Android Lifecycle
android-lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "androidLifeCycle" }
android-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidLifeCycle" }
android-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidLifeCycle" }
android-lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "androidLifeCycle" }
android-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidLifeCycle" }
android-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidLifeCycle" }
android-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidLifeCycle" }
# Google Core
google-ar-core = { group = "com.google.ar", name = "core", version.ref = "googleCore" }
# Jetpack Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
compose-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "composeActivity" }
compose-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "composeConstraintLayout" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material3-window-size-class = { group = "androidx.compose.material3", name = "material3-window-size-class" }
compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
# Hilt (Dagger)
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltVersion" }
# Hilt (AndroidX)
hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hiltNavigation" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltNavigation" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltNavigation" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation", version.ref = "hiltNavigation" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigation" }
hilt-navigation-fragment = { group = "androidx.hilt", name = "hilt-navigation-fragment", version.ref = "hiltNavigation" }
# Room Database
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
# Navigation
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navVersion" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navVersion" }
navigation-dynamic-features-fragment = { group = "androidx.navigation", name = "navigation-dynamic-features-fragment", version.ref = "navVersion" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navVersion" }

[plugins]